version: "3.8"

services:
  django_wsgi:
    build: .
    container_name: django_wsgi
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 -w 4
    volumes:
      - .:/app/
    expose:
      - 8000
    restart: always

  django_asgi:
    build: .
    container_name: django_wsgi
    command: daphne config.asgi:application -b 0.0.0.0 -p 8001
    volumes:
      - .:/app/
    expose:
      - 8000
    restart: always

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    depends_on:
      - django_asgi
      - django_wsgi
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static